#include "chat_core.hpp"
#include <iostream>
#include <stdexcept>
using namespace chime;
int checks=0;
void expect(bool condition,const char *label) {
    ++checks; if(!condition) throw std::runtime_error(label);
}
Message parse(const std::string &s) {
    Message m; expect(parseMessage(s,m),"valid chat parsed"); return m;
}
const std::string ts="[Sun Oct 04 20:35:17] ";
int main() {
    try {
        ChatHistory history;
        auto a=parse(ts+"Mela: First line.");
        auto b=parse(ts+"Khalen: [Tell] Second line.");
        history.add(a,"12:00:00"); history.add(b,"12:00:01");
        history.add(parse(ts+"mela: Third line."),"12:00:02");
        expect(history.speakers().size()==2,"history merges speaker case variants");
        expect(history.transcript("MELA").find("Third line.")!=std::string::npos,"history finds selected speaker case insensitively");
        expect(history.transcript("Mela").find("Second line.")==std::string::npos,"other character excluded from transcript");
        expect(history.transcript("").find("Second line.")!=std::string::npos,"all characters transcript");
        expect(history.transcript("Khalen").find("[Tell]")!=std::string::npos,"history retains channel");
        history.add(parse(ts+"Tor: Unselected line."),"12:00:03");
        auto combined=history.transcriptFor({"MELA","Khalen"});
        expect(combined.find("First line.")<combined.find("Second line.") && combined.find("Second line.")<combined.find("Third line."),"multiple speakers remain chronological");
        expect(combined.find("Unselected line.")==std::string::npos,"multi selection excludes others");
        expect(history.transcriptFor({}).empty(),"empty multi selection has no messages");
        expect(history.transcriptFor({},true).find("Unselected line.")!=std::string::npos,"all mode includes every character");
        history.entries.pop_back();
        history.limit=2; history.add(a,"12:00:03");
        expect(history.entries.size()==2 && history.entries.front().time=="12:00:02","history bounded and chronological");
        history.entries.clear(); expect(history.speakers().empty(),"history clear removes characters");
        history.limit=0; history.add(a,"12:00:04"); expect(history.entries.empty(),"zero history limit");
        auto local=parse(ts+"Mela: Good evening.");
        expect(local.channel==Channel::Talk && local.speaker=="Mela" && local.text=="Good evening.","unlabelled local speech");
        auto marked=parse("[CHAT WINDOW TEXT] "+ts+"Mela: [Whisper] Keep your voice down.");
        expect(marked.channel==Channel::Whisper && marked.text=="Keep your voice down.","whisper marker after name");
        expect(parse(ts+"[Talk] Mela: Hello.").channel==Channel::Talk,"channel before name");
        expect(parse(ts+"Mela: [Tell] Private message.").channel==Channel::Tell,"incoming tell");
        expect(parse(ts+"Mela: [Party] Group message.").channel==Channel::Party,"party marker");
        expect(parse(ts+"Mela: [Shout] Across the area.").channel==Channel::Shout,"shout marker");
        expect(parse(ts+"Mela: [DM] A DM message.").channel==Channel::DM,"DM marker");
        expect(parse(ts+"Mela: [Whisper]: A second format.").text=="A second format.","colon after channel");
        expect(parse(ts+"Mela: The [Shout] channel is loud.").channel==Channel::Talk,"channel words inside message do not change channel");
        expect(parse(ts+"Mela: [Basic] Hello, Khalen.").channel==Channel::Talk,"server language tags retained");
        expect(parse(ts+"Mela: *walks over and waves*").channel==Channel::Talk,"local RP emote");
        expect(parse(ts+"Mela: [Tell] 20:35 is the meeting time.").text=="20:35 is the meeting time.","colons inside message");
        auto outgoing=parse(ts+"To Mela: [Tell] My reply.");
        expect(outgoing.outgoing && outgoing.speaker=="Mela","outgoing tell prefix");
        expect(parse(ts+"From Mela: Private message.").channel==Channel::Tell,"incoming from prefix");
        expect(parse("\xEF\xBB\xBF"+ts+"Mela: Hi.").speaker=="Mela","UTF-8 BOM");
        expect(parse(ts+"<cfff000>Mela</c>: <cfff000>Hello.</c>").speaker=="Mela","NWN colour tags");
        expect(parse(ts+"Mela: H\xC3\xA9llo.").text=="H\xC3\xA9llo.","UTF-8 message preserved");
        Message rejected;
        expect(!parseMessage("Error: 40964",rejected),"engine output without chat prefix ignored");
        expect(!parseMessage(ts+"Server: Restarting in five minutes.",rejected),"server message ignored");
        expect(!parseMessage(ts+"[Event]: Area loaded.",rejected),"server event ignored");
        expect(!parseMessage("[CHAT WINDOW TEXT] "+ts+"Khalen attacks Mela: *hit* : (15 + 4 = 19)",rejected),"combat hit ignored");
        expect(!parseMessage("[CHAT WINDOW TEXT] "+ts+"Khalen damages Mela: 15 (Energy)",rejected),"combat damage ignored");
        expect(!parseMessage(ts+"Just an engine status line.",rejected),"non dialogue ignored");
        expect(!parseMessage(ts+"Mela: ",rejected),"empty message ignored");
        Filters filters;
        auto loading=parse(ts+"Loading Screen: Achievements in SWLOR are tied to your CD Key.");
        expect(!filters.matches(loading),"loading notice filtered by default");
        auto area=parse(ts+"Viscara - Jedi Temple Exterior: A place of peace and safety.");
        expect(!filters.matches(area),"pictured area description filtered");
        expect(filters.matches(parse(ts+"Mela: Loading Screen: I saw that tip too.")),"player quoting notice preserved");
        expect(filters.matches(parse(ts+"Mela: It is raining, and the air is humid.")),"player discussing weather preserved");
        expect(filters.matches(parse(ts+"Mela: *readies her blade*")),"player emote preserved");
        filters.ignoreSystem=false;
        expect(filters.matches(loading),"optional notice filter can be disabled");
        filters.ignoreSystem=true;
        expect(!parseMessage(ts+"[Server] You are now in a Full PVP Area.",rejected),"pictured PVP notice ignored");
        expect(!parseMessage(ts+"It is raining, and the air is humid.",rejected),"unnamed weather notice ignored");
        expect(!parseMessage(ts+"Khalen Vorr readies Burst of Speed II on Khalen Vorr.",rejected),"pictured action notice ignored");
        expect(!parseMessage("[COMBAT WINDOW TEXT] "+ts+"Mela: engine notice",rejected),"combat window excluded");
        expect(filters.matches(local),"default includes local");
        expect(filters.matches(marked),"default includes whisper");
        expect(!filters.matches(parse(ts+"Mela: [Party] Hello.")),"default excludes party");
        expect(!filters.matches(parse(ts+"Mela: [Shout] Hello.")),"default excludes shouts");
        expect(!filters.matches(parse(ts+"Mela: [DM] Hello.")),"DM disabled");
        expect(!filters.matches(outgoing),"outgoing tell never alerts");
        filters.ownNames=splitNames(" Khalen ; Khalen Soren ; ");
        expect(!filters.matches(parse(ts+"KHALEN: My own line.")),"case-insensitive exact own-name match");
        expect(!filters.matches(parse(ts+"Khalen Soren: My own line.")),"multiple full names");
        expect(filters.matches(parse(ts+"Khalenar: A different person.")),"similar names not excluded");
        filters.contains="Khalen";
        expect(filters.matches(parse(ts+"Mela: Hello, KHALEN.")),"case-insensitive text phrase");
        expect(!filters.matches(local),"nonmatching text phrase");
        filters.contains=""; filters.local=false;
        expect(!filters.matches(local),"local channel can be disabled");
        filters.party=true;
        expect(filters.matches(parse(ts+"Mela: [Party] Hello.")),"party channel can be enabled");
        LineBuffer stream; std::vector<std::string> lines;
        auto collect=[&](const std::string &s){lines.push_back(s);};
        stream.feed(ts+"Mela: H\xC3",collect); expect(lines.empty(),"partial line does not alert");
        stream.feed("\xA9llo.\r",collect); expect(lines.empty(),"CRLF split does not emit early");
        stream.feed("\n"+ts+"Mela: Second.\n",collect);
        expect(lines.size()==2 && lines[0]==ts+"Mela: H\xC3\xA9llo.","chunked UTF-8 and CRLF preserved");
        stream.reset(true); stream.feed("old partial\n"+ts+"Mela: New.\n",collect);
        expect(lines.size()==3 && lines.back()==ts+"Mela: New.","old partial skipped after seek to end");
        stream.reset(); stream.feed(std::string(131073,'x')+"\n"+ts+"Mela: Valid.\n",collect);
        expect(lines.size()==4 && lines.back()==ts+"Mela: Valid.","oversize line discarded without poisoning next message");
        TailCursor cursor;
        std::string disk=ts+"Mela: Historical chat.\n";
        std::vector<std::string> fresh;
        auto tailAt=[&](uint64_t offset) {
            if(offset>disk.size()) return std::string{};
            size_t n=static_cast<size_t>(std::min<uint64_t>(offset,64));
            return disk.substr(static_cast<size_t>(offset)-n,n);
        };
        auto poll=[&](bool skip,uint64_t id=17,uint64_t created=101,uint32_t volume=1) {
            cursor.prepare(disk.size(),id,created,volume,tailAt(cursor.offset),tailAt(disk.size()),skip);
            if(!skip && disk.size()>cursor.offset) {
                auto bytes=disk.substr(static_cast<size_t>(cursor.offset));
                cursor.consume(bytes,tailAt(disk.size()),[&](const std::string &line){fresh.push_back(line);});
            }
        };
        poll(true); poll(false);
        expect(fresh.empty() && cursor.offset==disk.size(),"existing history skipped on startup and arming");
        disk+=ts+"Mela: New speech.\n"; poll(false);
        expect(fresh.size()==1 && fresh.back()==ts+"Mela: New speech.","appended speech consumed once");
        poll(false); expect(fresh.size()==1,"same file poll never replays message");
        disk+=ts+"Mela: During OFF.\n"; poll(true); poll(true); poll(false);
        expect(fresh.size()==1,"messages during OFF discarded instead of queued");
        disk+=ts+"Mela: Split speech.\r"; poll(false);
        expect(fresh.size()==1,"log cursor holds incomplete write");
        disk+='\n'; poll(false); expect(fresh.size()==2,"log cursor completes split newline");
        disk=ts+"Mela: New session.\n"; poll(false);
        expect(fresh.size()==3 && fresh.back()==ts+"Mela: New session.","truncation and restart followed from beginning");
        disk=ts+"Mela: Rewritten "+std::string(300,'x')+"\n"; poll(false);
        expect(fresh.size()==4 && fresh.back().find("Rewritten")!=std::string::npos,"truncate-regrow beyond offset caught by anchor");
        disk=ts+"Mela: Replacement log.\n"; poll(false,18);
        expect(fresh.size()==5 && fresh.back()==ts+"Mela: Replacement log.","rotation with changed file identity followed");
        disk=ts+"Mela: Different creation.\n"; poll(false,18,102);
        expect(fresh.size()==6 && fresh.back()==ts+"Mela: Different creation.","same file index with new creation time followed");
        disk=ts+"Mela: Midway through an old line"; poll(true,18,102);
        disk+=" finishing\n"+ts+"Mela: After rearming.\n"; poll(false,18,102);
        expect(fresh.size()==7 && fresh.back()==ts+"Mela: After rearming.","partial historical line discarded when rearming");
        TailCursor newLog;
        newLog.prepare(15,19,102,1,"","",false);
        expect(newLog.initialized && newLog.offset==0,"new rolling file read from start while armed");
        AlertGate gate;
        expect(!gate.accept("old",100),"starts OFF");
        gate.setEnabled(true); expect(gate.accept("new",200),"first ON message alerts");
        expect(!gate.accept("another",300),"cooldown suppresses burst");
        expect(gate.accept("later",4200),"cooldown expiry alerts");
        gate.cooldownMs=100;
        expect(!gate.accept("later",4400),"same log line duplicated across files ignored");
        expect(gate.accept("later",7400),"dedup does not permanently suppress repeated chat");
        gate.setEnabled(false); expect(!gate.accept("off message",10000),"OFF remains silent");
        gate.setEnabled(true); expect(gate.accept("fresh",10001),"on/off clears previous cooldown");
        expect(!gate.accept("foreground",15000,true),"foreground-only suppression");
        expect(gate.accept("background",15001),"suppressed foreground message does not consume cooldown");
        const std::string input="\xEF\xBB\xBF# settings\r\n[game.log.chat.text]\r\n  enabled = false # keep this\r\n[unrelated]\r\nvalue = 7\r\n";
        auto updated=setSetting(input,"game.log.chat.text","enabled","true");
        expect(updated.find("  enabled = true # keep this\r\n")!=std::string::npos,"logging update keeps indentation, inline comment, CRLF");
        expect(starts(updated,"\xEF\xBB\xBF") && updated.find("[unrelated]\r\nvalue = 7\r\n")!=std::string::npos,"BOM and unrelated settings unchanged");
        expect(setSetting(updated,"game.log.chat.text","enabled","true")==updated,"logging setup idempotent");
        auto added=setSetting("[game.log.chat.text]\n# no key\n[next]\nx=1\n","game.log.chat.text","enabled","true");
        expect(added.find("enabled = true\n[next]")!=std::string::npos,"missing key inserted into correct section");
        auto missing=setSetting("[next]\nx=1","game.log.chat.text","enabled","true");
        expect(missing.find("[game.log.chat.text]\nenabled = true\n")!=std::string::npos,"missing logging section added");
        auto both=setSetting(missing,"game.log.chat.all","enabled","false");
        expect(both.find("[game.log.chat.all]\nenabled = false")!=std::string::npos,"entire chat logging disabled separately");
        auto legacy=setSetting("[Game Options]\r\nClientChatLogging=0\r\nOther=9\r\n","Game Options","ClientChatLogging","1");
        expect(legacy.find("ClientChatLogging= 1\r\nOther=9")!=std::string::npos,"classic NWN INI supported");
        std::cout<<"PASS: "<<checks<<" chat, filter, framing, on/off, cooldown and settings checks.\n";
        return 0;
    } catch(const std::exception &e) { std::cerr<<"FAIL: "<<e.what()<<" after "<<checks<<" checks.\n"; return 1; }
}
